# Generated by CoffeeScript 1.6.2
#
#Module dependencies.
#

#doesn't do anything noww
getSearchResult = (query) ->
  "searhc result of: " + query

#doesn't do anything now
validate = (data) ->
  data
  
querystring = require("querystring")
express = require("express")
routes = require("./routes")
firebase = require("firebase")
user = require("./routes/user")
http = require("http")
path = require("path")
feedsapi = require("./api/feeds.js")
fork = require("child_process").fork
app = express()
url = require("url")
querystring = require("querystring")
server = http.createServer(app)
io = require("socket.io").listen(server)
app.set "port", process.env.PORT or 3000
app.set "views", __dirname + "/views"
app.set "view engine", "jade"
app.use express.favicon()
app.use express.logger("dev")
app.use express.bodyParser()
app.use express.methodOverride()
app.use app.router
app.use express["static"](path.join(__dirname, "public"))
app.enable "trust proxy"
app.use express.errorHandler()  if "development" is app.get("env")
app.get "/", routes.index
app.get "/users", user.list

app.get "/api/feeds/note", (req, res) ->
  ###/feeds/note request###
  console.log "feeds/note api"
  urlData = url.parse(req.url)
  params = querystring.parse(urlData.query)
  
  validParams = feedsapi.validateNoteParam params 
  ###param validation###
  if validParams
    note = new firebase("https://wiredancer.firebaseio.com/note")
    note.once "value", (snapshot) -> 
      result = feedsapi.query snapshot.val(), 'note', validParams
      res.write result
      res.end()
  else
    res.write "Could not understand your request"
    res.end()

app.get "/api/feeds/user", (req, res) ->
  ###/feeds/user request###
  console.log "feeds/user api"
  urlData = url.parse(req.url)
  params = querystring.parse(urlData.query)
  
  validParams = feedsapi.validateUserParam params
  ###param validation###
  if validParams
    note = new firebase("https://wiredancer.firebaseio.com/user")
    note.once "value", (snapshot) -> 
      result = feedsapi.query snapshot.val(), 'user', validParams
      res.write result
      res.end()
  else
    res.write "Could not understand your request"
    res.end()  


server.listen app.get("port"), ->
  console.log "Express server listening on port " + app.get("port")
  0

io.sockets.on "connection", (socket) ->
  socket.send "hello from the game server"
  socket.on "search", (data) ->
    socket.emit "searchResult", getSearchResult(validate(data))

