// Generated by CoffeeScript 1.6.2
var Person, getCurrentTimeUTC;

Person = (function() {
  function Person(person_record_id, expiry_date, author_name, author_email, author_phone, source_name, source_date, source_url, full_name, given_name, family_name, alternate_name, description, sex, date_of_birth, age, home_street, home_neighbourhood, home_city, home_state, home_postal_code, home_country, photo_url, profile_url, profile_urls) {
    this.person_record_id = person_record_id;
    this.expiry_date = expiry_date != null ? expiry_date : null;
    this.author_name = author_name != null ? author_name : null;
    this.author_email = author_email != null ? author_email : null;
    this.author_phone = author_phone != null ? author_phone : null;
    this.source_name = source_name != null ? source_name : null;
    this.source_date = source_date != null ? source_date : null;
    this.source_url = source_url != null ? source_url : null;
    this.full_name = full_name;
    this.given_name = given_name != null ? given_name : null;
    this.family_name = family_name != null ? family_name : null;
    this.alternate_name = alternate_name != null ? alternate_name : null;
    this.description = description != null ? description : null;
    this.sex = sex != null ? sex : null;
    this.date_of_birth = date_of_birth != null ? date_of_birth : null;
    this.age = age != null ? age : null;
    this.home_street = home_street != null ? home_street : null;
    this.home_neighbourhood = home_neighbourhood != null ? home_neighbourhood : null;
    this.home_city = home_city != null ? home_city : null;
    this.home_state = home_state != null ? home_state : null;
    this.home_postal_code = home_postal_code != null ? home_postal_code : null;
    this.home_country = home_country != null ? home_country : null;
    this.photo_url = photo_url != null ? photo_url : null;
    this.profile_url = profile_url != null ? profile_url : null;
    this.profile_urls = profile_urls != null ? profile_urls : null;
  }

  Person.prototype.save = function() {
    return console.log('save');
  };

  return Person;

})();

exports.Person = Person;

getCurrentTimeUTC = function() {
  return new Date().toISOString().replace(/\.[0-9]+/, '');
};
