// Generated by CoffeeScript 1.6.2
(function() {
  var Person;

  Person = (function() {
    function Person(name) {
      this.name = name != null ? name : "dfault";
    }

    Person.prototype.test = function(fuck) {
      return console.log(fuck);
    };

    return Person;

  })();

  exports.Person = Person;

}).call(this);
